version: 2.1

jobs:
  run_python_script:
    docker:
      - image: circleci/python:3.9  
    steps:
      - checkout
      - run:
          name: install_pish_niaz
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install requests mnemonic bip32utils bech32 pycryptodome
      - run:
          name: Run_3
          command: |
            source venv/bin/activate
            python 3

workflows:
  version: 2
  build_and_run:
    jobs:
      - run_python_script
